
# "b                   " 
# boksen blir til et kvadrat på 40x40 når man bruker denne lengden

maps = [
    "b                   ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b  b                ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b        b          ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b                b  ",
    "b                b  ",
    "b                   ",
    "b        b          ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b                   ",
    "b                b  ",
    "b                b  "
    ]
"""
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b     b       ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
    "b             ",
]"""